/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * login.java
 *
 * Created on Feb 3, 2012, 6:19:13 AM
 */
package aplikasitoko;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.Statement;
import java.sql.ResultSet;
import javax.swing.ImageIcon;
import java.awt.Image;
/**
 *
 * @author fifin
 */
public class login extends Frame {

    /** Creates new form login */
    public login() {
        setLocationRelativeTo(null);
        setAnimationShow(Animation.SHOW_FROM_LEFT);
        setAnimationHide(Animation.SHOW_FROM_RIGHT);
        initComponents();
        ImageIcon icon = new ImageIcon(getClass().getResource("/aplikasitoko/gambar/ikon.jpg"));
        Image im=icon.getImage();
        setIconImage(im);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        textFieldStyle1 = new aplikasitoko.textFieldStyle();
        panelimage1 = new aplikasitoko.panelimage();
        panelalpa1 = new aplikasitoko.panelalpa();
        usr = new aplikasitoko.textFieldStyle();
        pass = new aplikasitoko.passwdTextStyle();
        jLabel1 = new javax.swing.JLabel();
        buttonStyle1 = new aplikasitoko.buttonStyle();
        panelImageAlpaUser1 = new aplikasitoko.panelImageAlpaUser();
        panelImageAlpaKunci1 = new aplikasitoko.panelImageAlpaKunci();
        jLabel2 = new javax.swing.JLabel();

        textFieldStyle1.setText("textFieldStyle1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("TOKO BUDI ANNOR");

        panelimage1.setBackground(new java.awt.Color(204, 51, 0));

        panelalpa1.setBackground(new java.awt.Color(255, 51, 51));
        panelalpa1.setLayout(null);

        usr.setName("usr"); // NOI18N
        usr.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                usrKeyReleased(evt);
            }
        });
        panelalpa1.add(usr);
        usr.setBounds(280, 30, 295, 47);

        pass.setEchoChar('*');
        pass.setName("pwd"); // NOI18N
        pass.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                passKeyReleased(evt);
            }
        });
        panelalpa1.add(pass);
        pass.setBounds(280, 100, 295, 51);

        jLabel1.setFont(new java.awt.Font("Arial", 1, 25));
        jLabel1.setForeground(new java.awt.Color(0, 51, 51));
        jLabel1.setText("Password");
        panelalpa1.add(jLabel1);
        jLabel1.setBounds(140, 100, 130, 50);

        buttonStyle1.setText("Login");
        buttonStyle1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonStyle1ActionPerformed(evt);
            }
        });
        panelalpa1.add(buttonStyle1);
        buttonStyle1.setBounds(320, 200, 160, 40);

        javax.swing.GroupLayout panelImageAlpaUser1Layout = new javax.swing.GroupLayout(panelImageAlpaUser1);
        panelImageAlpaUser1.setLayout(panelImageAlpaUser1Layout);
        panelImageAlpaUser1Layout.setHorizontalGroup(
            panelImageAlpaUser1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 140, Short.MAX_VALUE)
        );
        panelImageAlpaUser1Layout.setVerticalGroup(
            panelImageAlpaUser1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 130, Short.MAX_VALUE)
        );

        panelalpa1.add(panelImageAlpaUser1);
        panelImageAlpaUser1.setBounds(-10, -10, 140, 130);

        javax.swing.GroupLayout panelImageAlpaKunci1Layout = new javax.swing.GroupLayout(panelImageAlpaKunci1);
        panelImageAlpaKunci1.setLayout(panelImageAlpaKunci1Layout);
        panelImageAlpaKunci1Layout.setHorizontalGroup(
            panelImageAlpaKunci1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        panelImageAlpaKunci1Layout.setVerticalGroup(
            panelImageAlpaKunci1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        panelalpa1.add(panelImageAlpaKunci1);
        panelImageAlpaKunci1.setBounds(440, 220, 100, 100);

        jLabel2.setFont(new java.awt.Font("Arial", 1, 25));
        jLabel2.setForeground(new java.awt.Color(0, 51, 51));
        jLabel2.setText("User Name");
        panelalpa1.add(jLabel2);
        jLabel2.setBounds(130, 30, 130, 50);

        javax.swing.GroupLayout panelimage1Layout = new javax.swing.GroupLayout(panelimage1);
        panelimage1.setLayout(panelimage1Layout);
        panelimage1Layout.setHorizontalGroup(
            panelimage1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelimage1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelalpa1, javax.swing.GroupLayout.PREFERRED_SIZE, 602, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );
        panelimage1Layout.setVerticalGroup(
            panelimage1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelimage1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelalpa1, javax.swing.GroupLayout.PREFERRED_SIZE, 341, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(panelimage1, java.awt.BorderLayout.CENTER);

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-646)/2, (screenSize.height-399)/2, 646, 399);
    }// </editor-fold>//GEN-END:initComponents

private void usrKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_usrKeyReleased
if (evt.getKeyCode()==evt.VK_ENTER)
    pass.requestFocus();
}//GEN-LAST:event_usrKeyReleased

private void passKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_passKeyReleased
if (evt.getKeyCode()==evt.VK_ENTER)
    enterLogin();
}//GEN-LAST:event_passKeyReleased

private void buttonStyle1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonStyle1ActionPerformed
enterLogin();
}//GEN-LAST:event_buttonStyle1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new login().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private aplikasitoko.buttonStyle buttonStyle1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private aplikasitoko.panelImageAlpaKunci panelImageAlpaKunci1;
    private aplikasitoko.panelImageAlpaUser panelImageAlpaUser1;
    private aplikasitoko.panelalpa panelalpa1;
    private aplikasitoko.panelimage panelimage1;
    private aplikasitoko.passwdTextStyle pass;
    private aplikasitoko.textFieldStyle textFieldStyle1;
    private aplikasitoko.textFieldStyle usr;
    // End of variables declaration//GEN-END:variables
    fungsi fsu=new fungsi();
    void enterLogin()
    {
        if (usr.getText().length()<1)
        {
            javax.swing.JOptionPane.showMessageDialog(null, "Tulis User Name", "Pesan", 1);
            
        } else if (pass.getText().length()<1) {
            javax.swing.JOptionPane.showMessageDialog(null, "Tulis Password", "Pesan", 1);
        } else {
            
            try {
            Class.forName(fsu.klas).newInstance();
            Connection con = DriverManager.getConnection(fsu.klaSS);
            
            Statement sta = con.createStatement();
            String qry="select count(*) as jumlah from tb_user where namanya="
                    +fsu.fixSqlCharacter(usr.getText());
            ResultSet rs= sta.executeQuery(qry);
            if (rs.next())
                if (rs.getInt("jumlah")>0) {
                        qry="select count(*) as jumlah,kd_user from tb_user where namanya="
                            +fsu.fixSqlCharacter(usr.getText())+" and passwordnya="
                            +fsu.fixSqlCharacter(MD5(pass.getText()));
                        rs= sta.executeQuery(qry);
                        if (rs.next())
                            if (rs.getInt("jumlah")>0) {
                                fsu.normalKanBarang(rs.getString("kd_user"));
                                setVisible(false);
                                menukesatu mnu=new menukesatu();
                                mnu.pemakai=rs.getString("kd_user");
                                mnu.setVisible(true);
                            } else {
                                javax.swing.JOptionPane.showMessageDialog(null, "User atau Password salah", "Perhatian", 
                                        javax.swing.JOptionPane.INFORMATION_MESSAGE, null);
                            }
                } else {
                    javax.swing.JOptionPane.showMessageDialog(null, "User ini belum terdaftar", "Perhatian", 
                            javax.swing.JOptionPane.INFORMATION_MESSAGE, null);
                }
                
            rs.close();
            sta.close();
            con.close();
            } catch (Exception ex){
                if (fsu.idebugging)
                    System.out.println(" error enter login "+ex.getMessage());
            }
        }
    }
    
    String MD5(String md5) {
       try {
            java.security.MessageDigest md = java.security.MessageDigest.getInstance("MD5");
            byte[] array = md.digest(md5.getBytes());
            StringBuffer sb = new StringBuffer();
            for (int i = 0; i < array.length; ++i) {
              sb.append(Integer.toHexString((array[i] & 0xFF) | 0x100).substring(1,3));
           }
            return sb.toString();
        } catch (java.security.NoSuchAlgorithmException e) {
        }
        return null;
    }

}
