/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * menukesatu.java
 *
 * Created on Mar 6, 2012, 5:05:54 AM
 */
package aplikasitoko;

import java.awt.Toolkit;

/**
 *
 * @author amy
 */
public class menukesatu extends javax.swing.JFrame {

    /** Creates new form menukesatu */
    public menukesatu() {
        initComponents();
        setExtendedState(MAXIMIZED_BOTH);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelimagemenukesatu1 = new aplikasitoko.panelimagemenukesatu();
        try {
            panelalpa1 =(aplikasitoko.panelalpa)java.beans.Beans.instantiate(getClass().getClassLoader(), "aplikasitoko.menukesatu_panelalpa1");
        } catch (ClassNotFoundException e) {
            e.printStackTrace();
        } catch (java.io.IOException e) {
            e.printStackTrace();
        }
        tombolmenu1 = new aplikasitoko.tombolmenu();
        tombolmenu2 = new aplikasitoko.tombolmenu();
        tombolmenu3 = new aplikasitoko.tombolmenu();
        tombolmenu4 = new aplikasitoko.tombolmenu();
        bttransaksi1 = new aplikasitoko.bttransaksi();
        bttransaksi2 = new aplikasitoko.bttransaksi();
        btlapor1 = new aplikasitoko.btlapor();
        btlapor2 = new aplikasitoko.btlapor();
        btkeluar1 = new aplikasitoko.btkeluar();
        tombolmenu6 = new aplikasitoko.tombolmenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Menu Aplikasi");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });
        addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                formKeyPressed(evt);
            }
        });

        tombolmenu1.setText("Data User");
        tombolmenu1.setFont(new java.awt.Font("Arial Black", 0, 20));
        tombolmenu1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        tombolmenu1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tombolmenu1ActionPerformed(evt);
            }
        });

        tombolmenu2.setText("Data kostumer");
        tombolmenu2.setFont(new java.awt.Font("Arial Black", 0, 20));
        tombolmenu2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        tombolmenu2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tombolmenu2ActionPerformed(evt);
            }
        });

        tombolmenu3.setText("Data Barang");
        tombolmenu3.setFont(new java.awt.Font("Arial Black", 0, 20));
        tombolmenu3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        tombolmenu3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tombolmenu3ActionPerformed(evt);
            }
        });

        tombolmenu4.setText("Data Suplier");
        tombolmenu4.setFont(new java.awt.Font("Arial Black", 0, 20));
        tombolmenu4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        tombolmenu4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tombolmenu4ActionPerformed(evt);
            }
        });

        bttransaksi1.setText("Transaksi Beli");
        bttransaksi1.setFont(new java.awt.Font("Arial Black", 0, 20));
        bttransaksi1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttransaksi1ActionPerformed(evt);
            }
        });

        bttransaksi2.setText("Transaksi Jual");
        bttransaksi2.setFont(new java.awt.Font("Arial Black", 0, 20));
        bttransaksi2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttransaksi2ActionPerformed(evt);
            }
        });

        btlapor1.setText("Laporan Stok Barang");
        btlapor1.setFont(new java.awt.Font("Arial Black", 0, 20));
        btlapor1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btlapor1ActionPerformed(evt);
            }
        });

        btlapor2.setText("Laporan LABA/RUGI");
        btlapor2.setFont(new java.awt.Font("Arial Black", 0, 20));
        btlapor2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btlapor2ActionPerformed(evt);
            }
        });

        btkeluar1.setForeground(new java.awt.Color(0, 0, 204));
        btkeluar1.setText("Keluar");
        btkeluar1.setFont(new java.awt.Font("Arial Black", 1, 20));
        btkeluar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btkeluar1ActionPerformed(evt);
            }
        });

        tombolmenu6.setText("Data Gudang");
        tombolmenu6.setFont(new java.awt.Font("Arial Black", 0, 20));
        tombolmenu6.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        tombolmenu6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tombolmenu6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelalpa1Layout = new javax.swing.GroupLayout(panelalpa1);
        panelalpa1.setLayout(panelalpa1Layout);
        panelalpa1Layout.setHorizontalGroup(
            panelalpa1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelalpa1Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(panelalpa1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tombolmenu1, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tombolmenu3, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tombolmenu4, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(150, 150, 150)
                .addComponent(bttransaksi1, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(195, 195, 195)
                .addComponent(btlapor2, javax.swing.GroupLayout.PREFERRED_SIZE, 322, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(panelalpa1Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(tombolmenu2, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(150, 150, 150)
                .addComponent(bttransaksi2, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(185, 185, 185)
                .addComponent(btlapor1, javax.swing.GroupLayout.PREFERRED_SIZE, 322, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(panelalpa1Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(tombolmenu6, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(panelalpa1Layout.createSequentialGroup()
                .addGap(500, 500, 500)
                .addComponent(btkeluar1, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        panelalpa1Layout.setVerticalGroup(
            panelalpa1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelalpa1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(panelalpa1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelalpa1Layout.createSequentialGroup()
                        .addComponent(tombolmenu1, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(13, 13, 13)
                        .addComponent(tombolmenu3, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(13, 13, 13)
                        .addComponent(tombolmenu4, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelalpa1Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(bttransaksi1, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelalpa1Layout.createSequentialGroup()
                        .addGap(80, 80, 80)
                        .addComponent(btlapor2, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(13, 13, 13)
                .addGroup(panelalpa1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tombolmenu2, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bttransaksi2, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelalpa1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(btlapor1, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(3, 3, 3)
                .addComponent(tombolmenu6, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(83, 83, 83)
                .addComponent(btkeluar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout panelimagemenukesatu1Layout = new javax.swing.GroupLayout(panelimagemenukesatu1);
        panelimagemenukesatu1.setLayout(panelimagemenukesatu1Layout);
        panelimagemenukesatu1Layout.setHorizontalGroup(
            panelimagemenukesatu1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelimagemenukesatu1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(panelalpa1, javax.swing.GroupLayout.PREFERRED_SIZE, 1241, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(36, Short.MAX_VALUE))
        );
        panelimagemenukesatu1Layout.setVerticalGroup(
            panelimagemenukesatu1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelimagemenukesatu1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelalpa1, javax.swing.GroupLayout.PREFERRED_SIZE, 489, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(52, Short.MAX_VALUE))
        );

        panelalpa1.setPreferredSize(new java.awt.Dimension(Toolkit.getDefaultToolkit().getScreenSize().width-120,  Toolkit.getDefaultToolkit().getScreenSize().height-180));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelimagemenukesatu1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelimagemenukesatu1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-1313)/2, (screenSize.height-590)/2, 1313, 590);
    }// </editor-fold>//GEN-END:initComponents

private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
if (javax.swing.JOptionPane.showConfirmDialog(null, "Ingin Keluar dari Aplikasi?", "Perhatian", 
        javax.swing.JOptionPane.YES_NO_OPTION, 
        javax.swing.JOptionPane.QUESTION_MESSAGE)==javax.swing.JOptionPane.YES_OPTION)
    System.exit(0);
else {
    login lg =new login();
    this.setVisible(false);
    lg.setVisible(true);
}
}//GEN-LAST:event_formWindowClosing

private void btkeluar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btkeluar1ActionPerformed
System.exit(0);
}//GEN-LAST:event_btkeluar1ActionPerformed

private void tombolmenu3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tombolmenu3ActionPerformed
aplikasitoko.aplikasi.tbbarang frtbbarang=new aplikasitoko.aplikasi.tbbarang();
frtbbarang.setVisible(true);
}//GEN-LAST:event_tombolmenu3ActionPerformed

private void formKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyPressed
System.exit(0);
}//GEN-LAST:event_formKeyPressed

private void tombolmenu1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tombolmenu1ActionPerformed
aplikasitoko.aplikasi.tbdatauser fruser=new aplikasitoko.aplikasi.tbdatauser();
fruser.setVisible(true);
}//GEN-LAST:event_tombolmenu1ActionPerformed

private void tombolmenu4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tombolmenu4ActionPerformed
aplikasitoko.aplikasi.tbsuplier frsuplier=new aplikasitoko.aplikasi.tbsuplier();
frsuplier.setVisible(true);
}//GEN-LAST:event_tombolmenu4ActionPerformed

private void tombolmenu2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tombolmenu2ActionPerformed
aplikasitoko.aplikasi.tbkostumer frkostumer=new aplikasitoko.aplikasi.tbkostumer();
frkostumer.setVisible(true);
}//GEN-LAST:event_tombolmenu2ActionPerformed

private void bttransaksi1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttransaksi1ActionPerformed
aplikasitoko.aplikasi.trxbeli frtrxbeli=new aplikasitoko.aplikasi.trxbeli();
frtrxbeli.pemakai=pemakai;
frtrxbeli.setVisible(true);
}//GEN-LAST:event_bttransaksi1ActionPerformed

private void bttransaksi2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttransaksi2ActionPerformed
aplikasitoko.aplikasi.trxjual frtrxjual=new aplikasitoko.aplikasi.trxjual();
frtrxjual.pemakai=pemakai;
frtrxjual.setVisible(true);
}//GEN-LAST:event_bttransaksi2ActionPerformed

private void btlapor2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btlapor2ActionPerformed
aplikasitoko.laporan.rep_laporan fr_rep_laporan=new aplikasitoko.laporan.rep_laporan();
fr_rep_laporan.setVisible(true);
}//GEN-LAST:event_btlapor2ActionPerformed

private void btlapor1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btlapor1ActionPerformed
aplikasitoko.laporan.rep_lapbarang fr_rep_lapbarang=new aplikasitoko.laporan.rep_lapbarang();
fr_rep_lapbarang.setVisible(true);
}//GEN-LAST:event_btlapor1ActionPerformed

private void tombolmenu6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tombolmenu6ActionPerformed
aplikasitoko.aplikasi.dataGudang fr_dataGudang=new aplikasitoko.aplikasi.dataGudang();
fr_dataGudang.setVisible(true);
}//GEN-LAST:event_tombolmenu6ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(menukesatu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(menukesatu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(menukesatu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(menukesatu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new menukesatu().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private aplikasitoko.btkeluar btkeluar1;
    private aplikasitoko.btlapor btlapor1;
    private aplikasitoko.btlapor btlapor2;
    private aplikasitoko.bttransaksi bttransaksi1;
    private aplikasitoko.bttransaksi bttransaksi2;
    private aplikasitoko.panelalpa panelalpa1;
    private aplikasitoko.panelimagemenukesatu panelimagemenukesatu1;
    private aplikasitoko.tombolmenu tombolmenu1;
    private aplikasitoko.tombolmenu tombolmenu2;
    private aplikasitoko.tombolmenu tombolmenu3;
    private aplikasitoko.tombolmenu tombolmenu4;
    private aplikasitoko.tombolmenu tombolmenu6;
    // End of variables declaration//GEN-END:variables
public String pemakai="";
}
