/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * rep_laporan.java
 *
 * Created on May 28, 2012, 6:28:04 PM
 */
package aplikasitoko.laporan;

import aplikasitoko.Animation;
import aplikasitoko.Frame;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.Statement;
import java.sql.ResultSet;
import javax.swing.DefaultListModel;
import org.apache.commons.lang.StringEscapeUtils;
import java.awt.Color;

import java.awt.Component;
import java.awt.GridLayout;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;

import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JTable;
import javax.swing.LookAndFeel;
import javax.swing.table.JTableHeader;
import javax.swing.table.TableCellRenderer;


import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.text.MaskFormatter;

/**
 *
 * @author amy
 */
public class rep_lapbarang extends Frame {

    /** Creates new form rep_laporan */
    public rep_lapbarang() {
        initComponents();
        setExtendedState(MAXIMIZED_BOTH);
        setLocationRelativeTo(null);
        setAnimationHide(Animation.HIDE_TO_RIGHT);
        Date dt = new Date();
        String qry = "select nama_brg from tb_barang order by nama_brg";
        try {
            Class.forName(fsu.klas).newInstance();
            Connection con = DriverManager.getConnection(fsu.klaSS);
            Statement sta = con.createStatement();
            ResultSet rs = sta.executeQuery(qry);
            int i = 0;
            pilihBarang.insertItemAt("Pilih barang", i);
            while (rs.next()) {
                i++;
                pilihBarang.insertItemAt(rs.getString("nama_brg"), i);
            }
            pilihBarang.setSelectedIndex(0);
            sta.close();
            con.close();
        } catch (Exception ex) {
            if (fsu.idebugging) {
                System.out.println(" Salah nya " + ex.getMessage());
            }
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelimageLaporanlabarugi1 = new aplikasitoko.laporan.panelimageLaporanlabarugi("/aplikasitoko/gambar/lapran2.jpg");
        panelalpa1 = new aplikasitoko.panelalpa();
        labelklip2 = new aplikasitoko.aplikasi.labelklip();
        btkeluar1 = new aplikasitoko.btkeluar();
        btCetak = new aplikasitoko.buttonStyle();
        pilihBarang = new javax.swing.JComboBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        listModel = new DefaultListModel();
        daftarbarang = new javax.swing.JList(listModel);
        jLabel5 = new javax.swing.JLabel();
        btCetak1 = new aplikasitoko.buttonStyle();
        jLabel6 = new javax.swing.JLabel();
        txBrangini = new aplikasitoko.textFieldStyle();
        jLabel7 = new javax.swing.JLabel();

        setTitle("Laporan Laba / Rugi");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        panelimageLaporanlabarugi1.setLayout(null);

        panelalpa1.setBackground(new java.awt.Color(255, 255, 0));
        panelalpa1.setLayout(null);

        labelklip2.setText("Laporan Stok Barang");
        labelklip2.setFont(new java.awt.Font("Arial", 1, 36));
        panelalpa1.add(labelklip2);
        labelklip2.setBounds(430, 0, 400, 60);

        btkeluar1.setForeground(new java.awt.Color(0, 0, 204));
        btkeluar1.setText("Tutup");
        btkeluar1.setFont(new java.awt.Font("Arial Black", 1, 20));
        btkeluar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btkeluar1ActionPerformed(evt);
            }
        });
        panelalpa1.add(btkeluar1);
        btkeluar1.setBounds(20, 590, 230, 57);

        btCetak.setIcon(new javax.swing.ImageIcon(getClass().getResource("/aplikasitoko/gambar/print.png"))); // NOI18N
        btCetak.setMnemonic('K');
        btCetak.setText("Cetak");
        btCetak.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCetakActionPerformed(evt);
            }
        });
        panelalpa1.add(btCetak);
        btCetak.setBounds(530, 590, 200, 60);

        pilihBarang.setFont(new java.awt.Font("Arial", 1, 25));
        pilihBarang.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                pilihBarangFocusGained(evt);
            }
        });
        panelalpa1.add(pilihBarang);
        pilihBarang.setBounds(210, 70, 420, 50);

        daftarbarang.setFont(new java.awt.Font("Arial", 0, 25));
        daftarbarang.setToolTipText("Ini barang yang akan di cetak");
        daftarbarang.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                daftarbarangKeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(daftarbarang);

        panelalpa1.add(jScrollPane1);
        jScrollPane1.setBounds(210, 200, 960, 370);

        jLabel5.setFont(new java.awt.Font("Arial", 1, 25));
        jLabel5.setForeground(new java.awt.Color(0, 51, 51));
        jLabel5.setText("/");
        panelalpa1.add(jLabel5);
        jLabel5.setBounds(660, 70, 20, 50);

        btCetak1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/aplikasitoko/gambar/ikonbawah.png"))); // NOI18N
        btCetak1.setMnemonic('K');
        btCetak1.setText("Taruh ke tabel");
        btCetak1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCetak1ActionPerformed(evt);
            }
        });
        panelalpa1.add(btCetak1);
        btCetak1.setBounds(480, 130, 250, 60);

        jLabel6.setFont(new java.awt.Font("Arial", 1, 25));
        jLabel6.setForeground(new java.awt.Color(0, 51, 51));
        jLabel6.setText("<html>Daftar Barang yang akan dicetak</html>");
        panelalpa1.add(jLabel6);
        jLabel6.setBounds(20, 200, 180, 140);

        txBrangini.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txBranginiFocusGained(evt);
            }
        });
        panelalpa1.add(txBrangini);
        txBrangini.setBounds(700, 60, 470, 56);

        jLabel7.setFont(new java.awt.Font("Arial", 1, 25));
        jLabel7.setForeground(new java.awt.Color(0, 51, 51));
        jLabel7.setText("Pilih Barang");
        panelalpa1.add(jLabel7);
        jLabel7.setBounds(20, 70, 180, 50);

        panelimageLaporanlabarugi1.add(panelalpa1);
        panelalpa1.setBounds(50, 20, 1260, 660);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelimageLaporanlabarugi1, javax.swing.GroupLayout.PREFERRED_SIZE, 1333, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelimageLaporanlabarugi1, javax.swing.GroupLayout.PREFERRED_SIZE, 692, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
                        
private void btkeluar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btkeluar1ActionPerformed
    setVisible(false);
}//GEN-LAST:event_btkeluar1ActionPerformed
    
private void btCetakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCetakActionPerformed
    cetak();
}//GEN-LAST:event_btCetakActionPerformed
    
private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
    this.setVisible(false);
}//GEN-LAST:event_formWindowClosing
    
private void btCetak1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCetak1ActionPerformed
    
    if (pilihBarang.getSelectedIndex() != 0) {
        listModel.addElement(pilihBarang.getSelectedItem());
    }
    if (txBrangini.getText().length() > 0) {
        listModel.addElement(txBrangini.getText());
    }
}//GEN-LAST:event_btCetak1ActionPerformed
    
private void daftarbarangKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_daftarbarangKeyReleased
if (evt.getKeyCode()==evt.VK_DELETE) {
    listModel.remove(daftarbarang.getSelectedIndex());
}
}//GEN-LAST:event_daftarbarangKeyReleased

private void pilihBarangFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_pilihBarangFocusGained
txBrangini.setText("");
}//GEN-LAST:event_pilihBarangFocusGained

private void txBranginiFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txBranginiFocusGained
pilihBarang.setSelectedIndex(0);
}//GEN-LAST:event_txBranginiFocusGained

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(rep_lapbarang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(rep_lapbarang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(rep_lapbarang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(rep_lapbarang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            
            public void run() {
                new rep_lapbarang().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private aplikasitoko.buttonStyle btCetak;
    private aplikasitoko.buttonStyle btCetak1;
    private aplikasitoko.btkeluar btkeluar1;
    private javax.swing.JList daftarbarang;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private aplikasitoko.aplikasi.labelklip labelklip2;
    private aplikasitoko.panelalpa panelalpa1;
    private aplikasitoko.laporan.panelimageLaporanlabarugi panelimageLaporanlabarugi1;
    private javax.swing.JComboBox pilihBarang;
    private aplikasitoko.textFieldStyle txBrangini;
    // End of variables declaration//GEN-END:variables
    SimpleDateFormat sdf =
            new SimpleDateFormat("dd/MM/yyyy");
    DefaultListModel listModel;
    aplikasitoko.fungsi fsu = new aplikasitoko.fungsi();
    void cetak(){
        try {
        Class.forName(fsu.klas).newInstance();
        Connection con = DriverManager.getConnection(fsu.klaSS);
        Statement sta=con.createStatement(),stin=con.createStatement();
        String fileReport = fsu.getPath() + "rp_stokBarang.jasper";
        
        if (fsu.idebugging) {
            fileReport = "rp_stokBarang.jasper";
        }
        if (fsu.idebugging) {
            System.out.println(" t4 file jasper = " + fileReport);
        }
        String qryReport="SELECT kd_brg,format(stok,0) as stok,format(stok*hrg_beli,0) as asset, "
                + "kd_hrgbeli,hrg_beli,format(hrg_jual_grosir,0) as hrg_jual_grosir,"
                + "format(hrg_jual_retail,0) as hrg_jual_retail,satuan,nama_brg,(stok*hrg_beli) as assetv "
                + "FROM tb_barang ",miciini="";
        int i=0;
        if (listModel.getSize()>0) {
            for (i=0;i<listModel.getSize();i++) {
                if (i<1)
                {
                    miciini="'"+listModel.getElementAt(i)+"'";
                } else {
                    miciini+=",'"+listModel.getElementAt(i)+"'";
                }
            }
            qryReport+=" where nama_brg in ("+miciini+")";
        }
        
        String qry="select sum(assetv) as jumlah from ("+qryReport+") as data",totalUntung="0";
        ResultSet rs=sta.executeQuery(qry);
        if (rs.next()) {
                totalUntung=fsu.ceknullangka(rs.getString("jumlah"));
        }
        qry="select hrg_beli,kd_brg from ("+qryReport+") as data";
        rs=sta.executeQuery(qry);
        while (rs.next()) {
            qry="update tb_barang set kd_hrgbeli="+fsu.fixSqlCharacter(fsu.pengkodean(rs.getString("hrg_beli")))
                    +" where kd_brg="+fsu.fixSqlCharacter(rs.getString("kd_brg"));
            stin.executeUpdate(qry);
            
        }
        
        if (fsu.idebugging) System.out.println(" cek sum laporan laba rugi "+qry+" --- "+totalUntung);
        java.util.Map parameter = new java.util.HashMap();
        qryReport+=" order by kd_brg";
        parameter.put("qry", qryReport);
        parameter.put("jml", totalUntung);
        net.sf.jasperreports.engine.JasperPrint jasperPrint = net.sf.jasperreports.engine.JasperFillManager.fillReport(fileReport, parameter, con);
        //buat print
        if (fsu.printdeh) {
            net.sf.jasperreports.engine.JasperPrintManager.printReport(jasperPrint, false);
        } else {
            net.sf.jasperreports.view.JasperViewer jasperViewer = new net.sf.jasperreports.view.JasperViewer(jasperPrint, false);
            jasperViewer.setDefaultCloseOperation(javax.swing.JFrame.HIDE_ON_CLOSE);
            jasperViewer.setExtendedState(javax.swing.JFrame.MAXIMIZED_BOTH);
            jasperViewer.setTitle("Laporan");
            jasperViewer.setVisible(true);
        }
        sta.close();
        stin.close();
        con.close();
    } catch (Exception ex) {
        if (fsu.idebugging) {
            System.out.println(" salah di " + ex.getMessage());
        }
    }
    }
}
