/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * rep_laporan.java
 *
 * Created on May 28, 2012, 6:28:04 PM
 */
package aplikasitoko.laporan;

import aplikasitoko.Animation;
import aplikasitoko.Frame;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.Statement;
import java.sql.ResultSet;
import javax.swing.DefaultListModel;
import org.apache.commons.lang.StringEscapeUtils;
import java.awt.Color;

import java.awt.Component;
import java.awt.GridLayout;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;

import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JTable;
import javax.swing.LookAndFeel;
import javax.swing.table.JTableHeader;
import javax.swing.table.TableCellRenderer;


import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.text.MaskFormatter;

/**
 *
 * @author amy
 */
public class rep_laporan extends Frame {

    /** Creates new form rep_laporan */
    public rep_laporan() {
        initComponents();
        setExtendedState(MAXIMIZED_BOTH);
        setLocationRelativeTo(null);
        setAnimationHide(Animation.HIDE_TO_RIGHT);
        Date dt = new Date();
        tgl.setText(sdf.format(dt));
        tgl1.setText(sdf.format(dt));
        String qry = "select nama_brg from tb_barang order by nama_brg";
        try {
            Class.forName(fsu.klas).newInstance();
            Connection con = DriverManager.getConnection(fsu.klaSS);
            Statement sta = con.createStatement();
            ResultSet rs = sta.executeQuery(qry);
            int i = 0;
            pilihBarang.insertItemAt("Pilih barang", i);
            while (rs.next()) {
                i++;
                pilihBarang.insertItemAt(rs.getString("nama_brg"), i);
            }
            pilihBarang.setSelectedIndex(0);
            sta.close();
            con.close();
        } catch (Exception ex) {
            if (fsu.idebugging) {
                System.out.println(" Salah nya " + ex.getMessage());
            }
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dateChooserDialog1 = new datechooser.beans.DateChooserDialog();
        dateChooserDialog2 = new datechooser.beans.DateChooserDialog();
        panelimageLaporanlabarugi1 = new aplikasitoko.laporan.panelimageLaporanlabarugi("/aplikasitoko/gambar/laporan.jpg");
        panelalpa1 = new aplikasitoko.panelalpa();
        labelklip2 = new aplikasitoko.aplikasi.labelklip();
        tgl = new aplikasitoko.textMasking();
        pilihTgl = new aplikasitoko.buttonStyle();
        jLabel3 = new javax.swing.JLabel();
        tgl1 = new aplikasitoko.textMasking();
        pilihTgl1 = new aplikasitoko.buttonStyle();
        btkeluar1 = new aplikasitoko.btkeluar();
        btCetak = new aplikasitoko.buttonStyle();
        jLabel4 = new javax.swing.JLabel();
        pilihBarang = new javax.swing.JComboBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        listModel = new DefaultListModel();
        daftarbarang = new javax.swing.JList(listModel);
        jLabel5 = new javax.swing.JLabel();
        btCetak1 = new aplikasitoko.buttonStyle();
        jLabel6 = new javax.swing.JLabel();
        txBrangini = new aplikasitoko.textFieldStyle();
        btCetak2 = new aplikasitoko.buttonStyle();
        jLabel7 = new javax.swing.JLabel();

        dateChooserDialog1.setCurrentView(new datechooser.view.appearance.AppearancesList("Swing",
            new datechooser.view.appearance.ViewAppearance("custom",
                new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Tahoma", java.awt.Font.PLAIN, 11),
                    new java.awt.Color(0, 0, 0),
                    new java.awt.Color(0, 0, 255),
                    false,
                    true,
                    new datechooser.view.appearance.swing.ButtonPainter()),
                new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Tahoma", java.awt.Font.PLAIN, 11),
                    new java.awt.Color(0, 0, 0),
                    new java.awt.Color(0, 0, 255),
                    true,
                    true,
                    new datechooser.view.appearance.swing.ButtonPainter()),
                new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Tahoma", java.awt.Font.PLAIN, 11),
                    new java.awt.Color(0, 0, 255),
                    new java.awt.Color(0, 0, 255),
                    false,
                    true,
                    new datechooser.view.appearance.swing.ButtonPainter()),
                new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Tahoma", java.awt.Font.PLAIN, 11),
                    new java.awt.Color(128, 128, 128),
                    new java.awt.Color(0, 0, 255),
                    false,
                    true,
                    new datechooser.view.appearance.swing.LabelPainter()),
                new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Tahoma", java.awt.Font.PLAIN, 11),
                    new java.awt.Color(0, 0, 0),
                    new java.awt.Color(0, 0, 255),
                    false,
                    true,
                    new datechooser.view.appearance.swing.LabelPainter()),
                new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Tahoma", java.awt.Font.PLAIN, 11),
                    new java.awt.Color(0, 0, 0),
                    new java.awt.Color(255, 0, 0),
                    false,
                    false,
                    new datechooser.view.appearance.swing.ButtonPainter()),
                (datechooser.view.BackRenderer)null,
                false,
                true)));
    dateChooserDialog1.setCalendarPreferredSize(new java.awt.Dimension(700, 500));
    dateChooserDialog1.setWeekStyle(datechooser.view.WeekDaysStyle.FULL);
    dateChooserDialog1.setLocale(new java.util.Locale("in", "ID", ""));
    dateChooserDialog1.setNavigateFont(new java.awt.Font("Arial", java.awt.Font.PLAIN, 25));
    dateChooserDialog1.addSelectionChangedListener(new datechooser.events.SelectionChangedListener() {
        public void onSelectionChange(datechooser.events.SelectionChangedEvent evt) {
            dateChooserDialog1OnSelectionChange(evt);
        }
    });

    dateChooserDialog2.setCurrentView(new datechooser.view.appearance.AppearancesList("Swing",
        new datechooser.view.appearance.ViewAppearance("custom",
            new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Tahoma", java.awt.Font.PLAIN, 11),
                new java.awt.Color(0, 0, 0),
                new java.awt.Color(0, 0, 255),
                false,
                true,
                new datechooser.view.appearance.swing.ButtonPainter()),
            new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Tahoma", java.awt.Font.PLAIN, 11),
                new java.awt.Color(0, 0, 0),
                new java.awt.Color(0, 0, 255),
                true,
                true,
                new datechooser.view.appearance.swing.ButtonPainter()),
            new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Tahoma", java.awt.Font.PLAIN, 11),
                new java.awt.Color(0, 0, 255),
                new java.awt.Color(0, 0, 255),
                false,
                true,
                new datechooser.view.appearance.swing.ButtonPainter()),
            new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Tahoma", java.awt.Font.PLAIN, 11),
                new java.awt.Color(128, 128, 128),
                new java.awt.Color(0, 0, 255),
                false,
                true,
                new datechooser.view.appearance.swing.LabelPainter()),
            new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Tahoma", java.awt.Font.PLAIN, 11),
                new java.awt.Color(0, 0, 0),
                new java.awt.Color(0, 0, 255),
                false,
                true,
                new datechooser.view.appearance.swing.LabelPainter()),
            new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Tahoma", java.awt.Font.PLAIN, 11),
                new java.awt.Color(0, 0, 0),
                new java.awt.Color(255, 0, 0),
                false,
                false,
                new datechooser.view.appearance.swing.ButtonPainter()),
            (datechooser.view.BackRenderer)null,
            false,
            true)));
dateChooserDialog2.setCalendarPreferredSize(new java.awt.Dimension(700, 500));
dateChooserDialog2.setWeekStyle(datechooser.view.WeekDaysStyle.FULL);
dateChooserDialog2.setLocale(new java.util.Locale("in", "ID", ""));
dateChooserDialog2.setNavigateFont(new java.awt.Font("Arial", java.awt.Font.PLAIN, 25));
dateChooserDialog2.addSelectionChangedListener(new datechooser.events.SelectionChangedListener() {
    public void onSelectionChange(datechooser.events.SelectionChangedEvent evt) {
        dateChooserDialog2OnSelectionChange(evt);
    }
    });

    setTitle("Laporan Laba / Rugi");
    addWindowListener(new java.awt.event.WindowAdapter() {
        public void windowClosing(java.awt.event.WindowEvent evt) {
            formWindowClosing(evt);
        }
    });

    panelimageLaporanlabarugi1.setLayout(null);

    panelalpa1.setBackground(new java.awt.Color(0, 255, 153));
    panelalpa1.setLayout(null);

    labelklip2.setText("Laporan Laba / Rugi");
    labelklip2.setFont(new java.awt.Font("Arial", 1, 36));
    panelalpa1.add(labelklip2);
    labelklip2.setBounds(430, 0, 400, 60);

    tgl.addKeyListener(new java.awt.event.KeyAdapter() {
        public void keyReleased(java.awt.event.KeyEvent evt) {
            tglKeyReleased(evt);
        }
    });
    panelalpa1.add(tgl);
    tgl.setBounds(520, 60, 180, 47);

    pilihTgl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/aplikasitoko/gambar/tgl.png"))); // NOI18N
    pilihTgl.setMnemonic('d');
    pilihTgl.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            pilihTglActionPerformed(evt);
        }
    });
    panelalpa1.add(pilihTgl);
    pilihTgl.setBounds(730, 60, 70, 50);

    jLabel3.setFont(new java.awt.Font("Arial", 1, 25));
    jLabel3.setForeground(new java.awt.Color(0, 51, 51));
    jLabel3.setText("Sampai");
    panelalpa1.add(jLabel3);
    jLabel3.setBounds(360, 120, 120, 50);

    tgl1.addKeyListener(new java.awt.event.KeyAdapter() {
        public void keyReleased(java.awt.event.KeyEvent evt) {
            tgl1KeyReleased(evt);
        }
    });
    panelalpa1.add(tgl1);
    tgl1.setBounds(520, 120, 180, 47);

    pilihTgl1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/aplikasitoko/gambar/tgl.png"))); // NOI18N
    pilihTgl1.setMnemonic('d');
    pilihTgl1.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            pilihTgl1ActionPerformed(evt);
        }
    });
    panelalpa1.add(pilihTgl1);
    pilihTgl1.setBounds(730, 120, 70, 50);

    btkeluar1.setForeground(new java.awt.Color(0, 0, 204));
    btkeluar1.setText("Tutup");
    btkeluar1.setFont(new java.awt.Font("Arial Black", 1, 20));
    btkeluar1.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            btkeluar1ActionPerformed(evt);
        }
    });
    panelalpa1.add(btkeluar1);
    btkeluar1.setBounds(40, 590, 230, 57);

    btCetak.setIcon(new javax.swing.ImageIcon(getClass().getResource("/aplikasitoko/gambar/print.png"))); // NOI18N
    btCetak.setMnemonic('K');
    btCetak.setText("Cetak");
    btCetak.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            btCetakActionPerformed(evt);
        }
    });
    panelalpa1.add(btCetak);
    btCetak.setBounds(520, 590, 200, 60);

    jLabel4.setFont(new java.awt.Font("Arial", 1, 25));
    jLabel4.setForeground(new java.awt.Color(0, 51, 51));
    jLabel4.setText("Dari");
    panelalpa1.add(jLabel4);
    jLabel4.setBounds(360, 60, 120, 50);

    pilihBarang.setFont(new java.awt.Font("Arial", 1, 25));
    pilihBarang.addFocusListener(new java.awt.event.FocusAdapter() {
        public void focusGained(java.awt.event.FocusEvent evt) {
            pilihBarangFocusGained(evt);
        }
    });
    panelalpa1.add(pilihBarang);
    pilihBarang.setBounds(210, 270, 420, 50);

    daftarbarang.setFont(new java.awt.Font("Arial", 0, 25));
    daftarbarang.setToolTipText("Ini barang yang akan di cetak");
    daftarbarang.addKeyListener(new java.awt.event.KeyAdapter() {
        public void keyReleased(java.awt.event.KeyEvent evt) {
            daftarbarangKeyReleased(evt);
        }
    });
    jScrollPane1.setViewportView(daftarbarang);

    panelalpa1.add(jScrollPane1);
    jScrollPane1.setBounds(210, 395, 960, 190);

    jLabel5.setFont(new java.awt.Font("Arial", 1, 25));
    jLabel5.setForeground(new java.awt.Color(0, 51, 51));
    jLabel5.setText("/");
    panelalpa1.add(jLabel5);
    jLabel5.setBounds(660, 270, 20, 50);

    btCetak1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/aplikasitoko/gambar/ikonbawah.png"))); // NOI18N
    btCetak1.setMnemonic('K');
    btCetak1.setText("Taruh ke tabel");
    btCetak1.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            btCetak1ActionPerformed(evt);
        }
    });
    panelalpa1.add(btCetak1);
    btCetak1.setBounds(480, 330, 250, 60);

    jLabel6.setFont(new java.awt.Font("Arial", 1, 25));
    jLabel6.setForeground(new java.awt.Color(0, 51, 51));
    jLabel6.setText("<html>Daftar Barang yang akan dicetak</html>");
    panelalpa1.add(jLabel6);
    jLabel6.setBounds(20, 395, 180, 190);

    txBrangini.addFocusListener(new java.awt.event.FocusAdapter() {
        public void focusGained(java.awt.event.FocusEvent evt) {
            txBranginiFocusGained(evt);
        }
    });
    panelalpa1.add(txBrangini);
    txBrangini.setBounds(700, 260, 470, 56);

    btCetak2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/aplikasitoko/gambar/print.png"))); // NOI18N
    btCetak2.setMnemonic('K');
    btCetak2.setText("Cetak");
    btCetak2.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            btCetak2ActionPerformed(evt);
        }
    });
    panelalpa1.add(btCetak2);
    btCetak2.setBounds(500, 200, 200, 60);

    jLabel7.setFont(new java.awt.Font("Arial", 1, 25));
    jLabel7.setForeground(new java.awt.Color(0, 51, 51));
    jLabel7.setText("Pilih Barang");
    panelalpa1.add(jLabel7);
    jLabel7.setBounds(20, 270, 180, 50);

    panelimageLaporanlabarugi1.add(panelalpa1);
    panelalpa1.setBounds(50, 20, 1260, 660);

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addComponent(panelimageLaporanlabarugi1, javax.swing.GroupLayout.PREFERRED_SIZE, 1351, javax.swing.GroupLayout.PREFERRED_SIZE)
    );
    layout.setVerticalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(layout.createSequentialGroup()
            .addComponent(panelimageLaporanlabarugi1, javax.swing.GroupLayout.PREFERRED_SIZE, 692, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );

    pack();
    }// </editor-fold>//GEN-END:initComponents

private void tglKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tglKeyReleased
    if (evt.getKeyCode() == evt.VK_ENTER) {
        tgl1.requestFocus();
    }
}//GEN-LAST:event_tglKeyReleased
    
private void pilihTglActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pilihTglActionPerformed
    try {
        Date ini = (Date) sdf.parse(tgl.getText());
        dateChooserDialog1.setSelection(new datechooser.model.multiple.PeriodSet(new datechooser.model.multiple.Period(new java.util.GregorianCalendar((1900 + ini.getYear()), ini.getMonth(), ini.getDate()),
                new java.util.GregorianCalendar((1900 + ini.getYear()), ini.getMonth(), ini.getDate()))));
    } catch (Exception ex) {
        if (fsu.idebugging) {
            System.out.println("salah di pilihnota1ActionPerformed " + ex.getMessage());
        }
    }
    dateChooserDialog1.showDialog(null, true);
}//GEN-LAST:event_pilihTglActionPerformed
    
private void tgl1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tgl1KeyReleased
// TODO add your handling code here:
}//GEN-LAST:event_tgl1KeyReleased
    
private void pilihTgl1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pilihTgl1ActionPerformed
    try {
        Date ini = (Date) sdf.parse(tgl1.getText());
        dateChooserDialog2.setSelection(new datechooser.model.multiple.PeriodSet(new datechooser.model.multiple.Period(new java.util.GregorianCalendar((1900 + ini.getYear()), ini.getMonth(), ini.getDate()),
                new java.util.GregorianCalendar((1900 + ini.getYear()), ini.getMonth(), ini.getDate()))));
    } catch (Exception ex) {
        if (fsu.idebugging) {
            System.out.println("salah di pilihnota1ActionPerformed " + ex.getMessage());
        }
    }
    dateChooserDialog2.showDialog(null, true);
}//GEN-LAST:event_pilihTgl1ActionPerformed
            
private void btkeluar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btkeluar1ActionPerformed
    setVisible(false);
}//GEN-LAST:event_btkeluar1ActionPerformed
    
private void btCetakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCetakActionPerformed
    cetak(2);
}//GEN-LAST:event_btCetakActionPerformed
    
private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
    this.setVisible(false);
}//GEN-LAST:event_formWindowClosing
    
private void btCetak1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCetak1ActionPerformed
    
    if (pilihBarang.getSelectedIndex() != 0) {
        listModel.addElement(pilihBarang.getSelectedItem());
    }
    if (txBrangini.getText().length() > 0) {
        listModel.addElement(txBrangini.getText());
    }
}//GEN-LAST:event_btCetak1ActionPerformed
    
private void btCetak2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCetak2ActionPerformed
cetak(1);
}//GEN-LAST:event_btCetak2ActionPerformed

private void dateChooserDialog1OnSelectionChange(datechooser.events.SelectionChangedEvent evt) {//GEN-FIRST:event_dateChooserDialog1OnSelectionChange
    if (dateChooserDialog1.getSelectedDate() != null) {
        tgl.setText(sdf.format(dateChooserDialog1.getSelectedDate().getTime()));
    }
}//GEN-LAST:event_dateChooserDialog1OnSelectionChange

private void dateChooserDialog2OnSelectionChange(datechooser.events.SelectionChangedEvent evt) {//GEN-FIRST:event_dateChooserDialog2OnSelectionChange
    if (dateChooserDialog2.getSelectedDate() != null) {
        tgl1.setText(sdf.format(dateChooserDialog2.getSelectedDate().getTime()));
    }
}//GEN-LAST:event_dateChooserDialog2OnSelectionChange

private void daftarbarangKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_daftarbarangKeyReleased
if (evt.getKeyCode()==evt.VK_DELETE) {
    listModel.remove(daftarbarang.getSelectedIndex());
}
}//GEN-LAST:event_daftarbarangKeyReleased

private void pilihBarangFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_pilihBarangFocusGained
txBrangini.setText("");
}//GEN-LAST:event_pilihBarangFocusGained

private void txBranginiFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txBranginiFocusGained
pilihBarang.setSelectedIndex(0);
}//GEN-LAST:event_txBranginiFocusGained

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(rep_laporan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(rep_laporan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(rep_laporan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(rep_laporan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            
            public void run() {
                new rep_laporan().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private aplikasitoko.buttonStyle btCetak;
    private aplikasitoko.buttonStyle btCetak1;
    private aplikasitoko.buttonStyle btCetak2;
    private aplikasitoko.btkeluar btkeluar1;
    private javax.swing.JList daftarbarang;
    private datechooser.beans.DateChooserDialog dateChooserDialog1;
    private datechooser.beans.DateChooserDialog dateChooserDialog2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private aplikasitoko.aplikasi.labelklip labelklip2;
    private aplikasitoko.panelalpa panelalpa1;
    private aplikasitoko.laporan.panelimageLaporanlabarugi panelimageLaporanlabarugi1;
    private javax.swing.JComboBox pilihBarang;
    private aplikasitoko.buttonStyle pilihTgl;
    private aplikasitoko.buttonStyle pilihTgl1;
    private aplikasitoko.textMasking tgl;
    private aplikasitoko.textMasking tgl1;
    private aplikasitoko.textFieldStyle txBrangini;
    // End of variables declaration//GEN-END:variables
    SimpleDateFormat sdf =
            new SimpleDateFormat("dd/MM/yyyy");
    DefaultListModel listModel;
    aplikasitoko.fungsi fsu = new aplikasitoko.fungsi();
    void cetak(int pilih){
        try {
        Class.forName(fsu.klas).newInstance();
        Connection con = DriverManager.getConnection(fsu.klaSS);
        Statement sta=con.createStatement(),stin=con.createStatement();
        String fileReport = fsu.getPath() + "rp_labarugi.jasper";
        
        if (fsu.idebugging) {
            fileReport = "rp_labarugi.jasper";
        }
        if (fsu.idebugging) {
            System.out.println(" t4 file jasper = " + fileReport);
        }
        String qryReport="select a.nota, a.kd_brg,b.nama_brg, a.kd_hrgbeli,a.hrg_beli,format(a.hrg_jual,0) as hrg_jual,"
                + "format(a.discount,0) as discount, format(a.selisih,0) as selisih,format(a.stok,0) as stok,selisih as selisihv, "
                + "b.satuan "
                + "from tb_trxjual1 a "
                + "join tb_barang b on a.kd_brg=b.kd_brg "
                + "join tb_trxjual c on a.nota=c.nota "
                + "where a.nota is not null ",miciini="";
        int i=0;
        if (!tgl.getText().equalsIgnoreCase("__/__/____")&&!tgl1.getText().equalsIgnoreCase("__/__/____")) {
            qryReport+=" and date(c.tanggal) between "
                    + " STR_TO_DATE("+fsu.fixSqlCharacter(tgl.getText())+", '%d/%m/%Y') "
                    + " and STR_TO_DATE("+fsu.fixSqlCharacter(tgl1.getText())+", '%d/%m/%Y') ";
        }
        
        if (listModel.getSize()>0&&pilih==2) {
            for (i=0;i<listModel.getSize();i++) {
                if (i<1)
                {
                    miciini="'"+listModel.getElementAt(i)+"'";
                } else {
                    miciini+=",'"+listModel.getElementAt(i)+"'";
                }
            }
            qryReport+=" and b.nama_brg in ("+miciini+")";
        }
        if (fsu.idebugging) System.out.println(" cek laporan laba rugi "+qryReport);
        String qry="select sum(selisihv) as jumlah from ("+qryReport+") as data",totalUntung="0";
        ResultSet rs=sta.executeQuery(qry);
        if (rs.next()) {
                totalUntung=fsu.ceknullangka(rs.getString("jumlah"));
        }
        qry="select hrg_beli,kd_brg,nota from ("+qryReport+") as data";
        rs=sta.executeQuery(qry);
        while (rs.next()) {
            qry="update tb_trxjual1 set kd_hrgbeli="+fsu.fixSqlCharacter(fsu.pengkodean(rs.getString("hrg_beli")))
                    +" where nota="+fsu.fixSqlCharacter(rs.getString("nota"))
                    +" and kd_brg="+fsu.fixSqlCharacter(rs.getString("kd_brg"));
            stin.executeUpdate(qry);
            
        }
        
        if (fsu.idebugging) System.out.println(" cek sum laporan laba rugi "+qry+" --- "+totalUntung);
        java.util.Map parameter = new java.util.HashMap();
        parameter.put("tgl", tgl.getText());
        parameter.put("tgl1", tgl1.getText());
        qryReport+=" order by a.nota";
        parameter.put("qry", qryReport);
        parameter.put("totaluntung", totalUntung);
        net.sf.jasperreports.engine.JasperPrint jasperPrint = net.sf.jasperreports.engine.JasperFillManager.fillReport(fileReport, parameter, con);
        //buat print
        if (fsu.printdeh) {
            net.sf.jasperreports.engine.JasperPrintManager.printReport(jasperPrint, false);
        } else {
            net.sf.jasperreports.view.JasperViewer jasperViewer = new net.sf.jasperreports.view.JasperViewer(jasperPrint, false);
            jasperViewer.setDefaultCloseOperation(javax.swing.JFrame.HIDE_ON_CLOSE);
            jasperViewer.setExtendedState(javax.swing.JFrame.MAXIMIZED_BOTH);
            jasperViewer.setTitle("Laporan");
            jasperViewer.setVisible(true);
        }
        sta.close();
        stin.close();
        con.close();
    } catch (Exception ex) {
        if (fsu.idebugging) {
            System.out.println(" salah di " + ex.getMessage());
        }
    }
    }
}
