/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * tbbarang.java
 *
 * Created on Mar 10, 2012, 5:52:46 AM
 */
package aplikasitoko.aplikasi;

import aplikasitoko.Animation;
import aplikasitoko.Frame;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.Statement;
import java.sql.ResultSet;
import org.apache.commons.lang.StringEscapeUtils;
import java.awt.Color;

import java.awt.Component;
import java.awt.GridLayout;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;

import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JTable;
import javax.swing.LookAndFeel;
import javax.swing.table.JTableHeader;
import javax.swing.table.TableCellRenderer;

/**
 *
 * @author amy
 */
public class dataGudang extends Frame {

    /** Creates new form tbbarang */
    public dataGudang() {
        initComponents();
        setExtendedState(MAXIMIZED_BOTH);
        setLocationRelativeTo(null);
        setAnimationHide(Animation.HIDE_TO_RIGHT);

    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        imageGlass1 = new aplikasitoko.aplikasi.imageGlass();
        btOutput = new aplikasitoko.buttonStyle();
        btinput = new aplikasitoko.buttonStyle();
        btkeluar1 = new aplikasitoko.btkeluar();
        panelTransparant1 = new aplikasitoko.aplikasi.panelTransparant();
        jLabel1 = new javax.swing.JLabel();

        setTitle("Data Barang");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        imageGlass1.setLayout(null);

        btOutput.setIcon(new javax.swing.ImageIcon(getClass().getResource("/aplikasitoko/gambar/tambah.gif"))); // NOI18N
        btOutput.setMnemonic('O');
        btOutput.setText("Output Barang");
        btOutput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btOutputActionPerformed(evt);
            }
        });
        imageGlass1.add(btOutput);
        btOutput.setBounds(680, 600, 220, 60);

        btinput.setIcon(new javax.swing.ImageIcon(getClass().getResource("/aplikasitoko/gambar/tambah.gif"))); // NOI18N
        btinput.setMnemonic('I');
        btinput.setText("Input Barang");
        btinput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btinputActionPerformed(evt);
            }
        });
        imageGlass1.add(btinput);
        btinput.setBounds(410, 600, 220, 60);

        btkeluar1.setForeground(new java.awt.Color(0, 0, 204));
        btkeluar1.setText("Tutup");
        btkeluar1.setFont(new java.awt.Font("Arial Black", 1, 20));
        btkeluar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btkeluar1ActionPerformed(evt);
            }
        });
        imageGlass1.add(btkeluar1);
        btkeluar1.setBounds(30, 600, 230, 57);

        panelTransparant1.setLayout(null);

        jLabel1.setText("jLabel1");
        panelTransparant1.add(jLabel1);
        jLabel1.setBounds(130, 60, 34, 14);

        imageGlass1.add(panelTransparant1);
        panelTransparant1.setBounds(70, 30, 1020, 520);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(imageGlass1, javax.swing.GroupLayout.DEFAULT_SIZE, 1243, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(imageGlass1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 680, Short.MAX_VALUE)
        );

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-1259)/2, (screenSize.height-718)/2, 1259, 718);
    }// </editor-fold>//GEN-END:initComponents

private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
    this.setVisible(false);
}//GEN-LAST:event_formWindowClosing

private void btOutputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btOutputActionPerformed
    
}//GEN-LAST:event_btOutputActionPerformed

private void btinputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btinputActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_btinputActionPerformed

private void btkeluar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btkeluar1ActionPerformed
    setVisible(false);
}//GEN-LAST:event_btkeluar1ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private aplikasitoko.buttonStyle btOutput;
    private aplikasitoko.buttonStyle btinput;
    private aplikasitoko.btkeluar btkeluar1;
    private aplikasitoko.aplikasi.imageGlass imageGlass1;
    private javax.swing.JLabel jLabel1;
    private aplikasitoko.aplikasi.panelTransparant panelTransparant1;
    // End of variables declaration//GEN-END:variables
   
}
